customhost = "employee.cesetupnsipd.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "bait3273"
customdb = "employee"
custombucket = "khorhuiliang-employee"
customregion = "us-east-1"
